# Generated by Django 4.2.24 on 2026-01-07 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0002_remove_sellerprofile_store_post_code_and_more'),
        ('products', '0001_initial'),
        ('customers', '0005_alter_customerprofile_phone_number_and_more'),
        ('orders', '0004_alter_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], default='percentage', max_length=50, verbose_name='Discount type')),
                ('scope_type', models.CharField(choices=[('all_customers_all_products', 'All Customers - All Products'), ('all_customers_specific_products', 'All Customers - Specific Products'), ('specific_customer_all_products', 'Specific Customer - All Products'), ('specific_customer_specific_products', 'Specific Customer - Specific Products')], max_length=50, verbose_name='Scope type')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Value')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is used')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='used at')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start day')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end day')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_by', to='customers.customerprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SiteDiscount',
            fields=[
                ('basediscount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='discounts.basediscount')),
                ('target_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_discount', to='customers.customerprofile')),
                ('target_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_discount', to='products.product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=('discounts.basediscount',),
        ),
        migrations.CreateModel(
            name='SellerDiscount',
            fields=[
                ('basediscount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='discounts.basediscount')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_discounts', to='sellers.sellerprofile')),
                ('target_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_discounts', to='customers.customerprofile')),
                ('target_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_discounts', to='products.product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=('discounts.basediscount',),
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(max_length=50, verbose_name='Discount code')),
                ('discount_type', models.CharField(max_length=50, verbose_name='Discount type')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount value')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount amount')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='used at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to='customers.customerprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to='orders.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to='orders.orderitem')),
                ('seller_discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='discounts.sellerdiscount')),
                ('site_discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='discounts.sitediscount')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
