# Generated by Django 5.2.11 on 2026-02-22 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customerprofile_phone_number_and_more'),
        ('discounts', '0001_initial'),
        ('products', '0002_remove_product_seller_product_store'),
        ('sellers', '0003_remove_sellerprofile_physical_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountusage',
            name='seller_discount',
        ),
        migrations.CreateModel(
            name='StoreDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], default='percentage', max_length=50, verbose_name='Discount type')),
                ('scope_type', models.CharField(choices=[('all_customers_all_products', 'All Customers - All Products'), ('all_customers_specific_products', 'All Customers - Specific Products'), ('specific_customer_all_products', 'Specific Customer - All Products'), ('specific_customer_specific_products', 'Specific Customer - Specific Products')], max_length=50, verbose_name='Scope type')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Value')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is used')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='used at')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start day')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end day')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_discounts', to='sellers.store')),
                ('target_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_discounts', to='customers.customerprofile')),
                ('target_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_discounts', to='products.product')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_used_by', to='customers.customerprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='discountusage',
            name='store_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='discounts.storediscount'),
        ),
        migrations.DeleteModel(
            name='SellerDiscount',
        ),
    ]
