# Generated by Django 4.2.24 on 2026-01-03 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customerprofile_phone_number_and_more'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basediscount',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_by', to='customers.customerprofile'),
        ),
    ]
