# Generated by Django 4.2.24 on 2026-01-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_basediscount_used_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountusage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
