# Generated by Django 4.2.24 on 2025-09-30 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Phone Number')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='address')),
                ('store_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='store name')),
                ('physical_store', models.BooleanField(default=True, verbose_name='Physical Store')),
                ('store_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='store Address')),
                ('store_post_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Store Post Code')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='national Code')),
                ('id_card_picture', models.ImageField(blank=True, null=True, upload_to='customer/id_card_pics', verbose_name='ID card picture')),
                ('birth_day', models.DateField(blank=True, null=True, verbose_name='Birth day')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
