# Generated by Django 4.2.24 on 2025-11-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='store_post_code',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='post_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Post Code'),
        ),
    ]
