# Generated by Django 5.2.11 on 2026-02-21 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_remove_sellerprofile_store_post_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='physical_store',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='store_address',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='store_name',
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='id_card_picture',
            field=models.ImageField(blank=True, null=True, upload_to='seller/id_card_pics', verbose_name='ID card picture'),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50, verbose_name='store name')),
                ('store_phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='phone number')),
                ('physical_store', models.BooleanField(default=True, verbose_name='Physical Store')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('store_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='store Address')),
                ('store_post_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Post Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='sellers.sellerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
