# Generated by Django 4.2.24 on 2025-09-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_address_remove_user_birth_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_roll',
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('customer', 'customer'), ('seller', 'seller')], default=1, max_length=10, verbose_name='Role'),
            preserve_default=False,
        ),
    ]
