# Generated by Django 4.2.24 on 2025-09-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='Birth day'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(default=None, max_length=11, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='post_code',
            field=models.CharField(default=0, max_length=10, verbose_name='Post Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='id_card_picture',
            field=models.ImageField(blank=True, null=True, upload_to='customer/id_card_pics', verbose_name='ID card picture'),
        ),
    ]
