# Generated by Django 4.2.24 on 2025-09-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerprofile_address_customerprofile_birth_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='customer/profile_pics', verbose_name='profile avatar'),
        ),
    ]
