# Generated by Django 4.2.24 on 2025-09-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customerprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='post_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Post Code'),
        ),
    ]
