# Generated by Django 5.2.11 on 2026-02-25 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_wallet_transaction'),
        ('orders', '0004_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('top_up', 'Top Up'), ('order_payment', 'Order Payment'), ('refund', 'Refund')], max_length=50, verbose_name='Transaction Type'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_cannot_be_negative'),
        ),
    ]
