# Generated by Django 4.2.24 on 2025-11-29 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0005_alter_customerprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='order_number')),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=30, verbose_name='order_status')),
                ('shipping_city', models.CharField(max_length=30, verbose_name='shipping_city')),
                ('shipping_address', models.CharField(max_length=100, verbose_name='shipping_address')),
                ('shipping_post_code', models.CharField(max_length=30, verbose_name='shipping_post_code')),
                ('shipping_phone', models.CharField(max_length=11, verbose_name='shipping_phone')),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='total_price')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('wallet', 'Wallet'), ('credit card', 'Credit Card')], max_length=30, verbose_name='payment_method')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is_paid')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
