# Generated by Django 4.2.24 on 2025-12-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_created_at_alter_order_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='store_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Store Name'),
            preserve_default=False,
        ),
    ]
