# Generated by Django 4.2.24 on 2025-11-29 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0002_remove_sellerprofile_store_post_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Product name')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Price')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category')),
                ('in_stock', models.BooleanField(default=True, verbose_name='In stock')),
                ('picture', models.ImageField(blank=True, max_length=4, null=True, upload_to='products/pictures', verbose_name='Product picture')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='sellers.sellerprofile')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
